# Generated by Django 2.2.3 on 2019-08-06 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, max_length=100, verbose_name='IP地址')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='功能描述')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='設備品牌')),
                ('zcmodel', models.CharField(blank=True, max_length=50, verbose_name='設備型號')),
                ('zcnumber', models.CharField(blank=True, max_length=50, verbose_name='設備序號')),
                ('zcpz', models.CharField(blank=True, max_length=100, verbose_name='設備配置')),
                ('undernet', models.CharField(max_length=10, verbose_name='所在地方')),
                ('guartime', models.CharField(blank=True, max_length=50, verbose_name='保修期')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='備註')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改時間')),
            ],
            options={
                'verbose_name': '資產表',
                'verbose_name_plural': '資產表',
            },
        ),
        migrations.CreateModel(
            name='ServerHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverid', models.IntegerField(verbose_name='資產ID')),
                ('zctype', models.CharField(max_length=20, verbose_name='資產類型')),
                ('ipaddress', models.CharField(blank=True, max_length=100, verbose_name='IP地址')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='功能描述')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='設備品牌')),
                ('zcmodel', models.CharField(blank=True, max_length=50, verbose_name='設備型號')),
                ('zcnumber', models.CharField(blank=True, max_length=50, verbose_name='設備序號')),
                ('zcpz', models.CharField(blank=True, max_length=100, verbose_name='設備配置')),
                ('owner', models.CharField(max_length=20, verbose_name='管理人員')),
                ('undernet', models.CharField(max_length=10, verbose_name='所在地方')),
                ('guartime', models.CharField(blank=True, max_length=50, verbose_name='保修期')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='備註')),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改時間')),
            ],
            options={
                'verbose_name': '資產歷史表',
                'verbose_name_plural': '資產歷史表',
            },
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zctype', models.CharField(max_length=20, verbose_name='資產類型')),
            ],
            options={
                'verbose_name': '資產類型表',
                'verbose_name_plural': '資產類型表',
            },
        ),
    ]
