# Generated by Django 2.2.3 on 2021-07-01 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20190806_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='undernet',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='modify_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时間'),
        ),
    ]
